[package]
name = "talc-aarch64"
version = "0.1.0"
edition = "2021"

[dependencies]
disarm64 = "0.1.20"
paste = "1.0.15"
portal-pc-waffle.workspace = true
talc-common = { version = "0.1.0", path = "../talc-common" }
waffle-ast.workspace = true
