[package]
name = "talc-mimd"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.13.0"
generic-array = "1.1.1"
paste = "1.0.15"
portal-pc-waffle.workspace = true
talc-common = { version = "0.1.0", path = "../talc-common" }
typenum = "1.17.0"
waffle-ast.workspace = true
