[package]
name = "talc-felf"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
portal-pc-waffle.workspace = true
talc-common = { version = "0.1.0", path = "../talc-common" }
typenum = "1.17.0"
waffle-ast.workspace = true
