[package]
name = "talc-mips"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
portal-pc-waffle.workspace = true
rabbitizer = "1.12.5"

talc-common = { version = "0.1.0", path = "../talc-common" }
waffle-ast.workspace = true
